"""Adjust phone column for Twilio format

Revision ID: 53910c160760
Revises: b74198b506c5
Create Date: 2025-10-18 15:39:58.184785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53910c160760'
down_revision = 'b74198b506c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
