"""Add category to Tip

Revision ID: d2f30339f39e
Revises: 53910c160760
Create Date: 2025-10-22 16:29:24.466449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f30339f39e'
down_revision = '53910c160760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tips', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
